#ifndef LABIRINTOSO_CONSTANTES_H
#define LABIRINTOSO_CONSTANTES_H

#define TAMANHO_COMANDO 100
#define TAMANHO_NAMES 50

#define MAX_USERS 5
#define MAX_BOTS 10
#define MAX_ROCKS 50
#define MAX_BLOCKS 5
#define MAX_LEVELS 3

#define MAP_WIDTH 40
#define MAP_HEIGHT 16

#define TEMPO_INSCRICAO 20
#define TEMPO_DURACAO 120
#define TEMPO_DECREMENTO 10

#define CHAR_ROCK 'R'
#define CHAR_BLOCK 'B'
#define CHAR_WALL 'X'

#endif